### ISSUE TITLE
FN layer issues

### ISSUE THREAD

**Issue by dfunkt** [ah-/anne-key#13]
The "delete", "insert" and "print screen" combinations do not seem to work for me, the others seem to be fine. Using the release from commit https://github.com/ah-/anne-key/commit/79207b04e91e61dccb10d22b2a454c9492b14fbb on Windows 10.

**Comment by ah-** [comment]
Thanks for reporting this! Not sure about PrintScreen (maybe that needs a different scan code?), but it looks like Insert and Delete might be in the wrong place here: https://github.com/ah-/anne-key/commit/79207b04e91e61dccb10d22b2a454c9492b14fbb#diff-2bf12c18e1c16f056969a0c223e6485eR41

On the base layout these two keys are marked as `No` which means they don't have a switch wired to them, they're just blanks under the right shift key. So probably the `FN` layout needs tweaking, want to send a PR that moves those two keys to where they should be?

**Comment by dfunkt** [comment]
Can confirm that it's working fine now, closing the issue.

**Comment by dfunkt** [comment]
Actually, I forgot that I made this issue about PScreen too lol, silly me.

**Comment by ah-** [comment]
Ha, great. Was just about to write that I have no idea what PScreen could be about :)
