### ISSUE TITLE
[feature] reset to DFU mode in software

### ISSUE THREAD

**Issue by hdhoang** [ah-/anne-key#44]
I would like to initiate reset to DFU without having to flip the keyboard and poke the reset pin. AIUI, booting with the Escape key down enters DFU mode, so I imagined binding a key-combo with Escape to reset the key MCU would do the job.

In https://github.com/hdhoang/anne-key/commit/13c9604c1b0da2c9d9411ea85422d932fed25a6e
I have given the SCB to `Keyboard`, then tried to write the reset request when processing `Action::Reset`. Though the `set_theme(3)` call worked, the keyboard went  on working normally instead of resetting.

Some paths I would like to explore next:

- maybe I need to write to AIRCR differently?
- maybe I need to move SCB base back to bootloader's position so that the CPU starts there after reset?

Nikkelitous also said people normally reset MCU from the host side instead of requesting it to reset itself :)

Please advise me on how to implement this!

**Comment by ah-** [comment]
This looks about right to me.

Possibly `unsafe { scb.aircr.modify(|v| v | (0x05fa << 16) | 0b100) }` has some bits set in v that you might not want, maybe try just ` unsafe { scb.aircr.modify(|v| (0x05fa << 16) | 0b100) }`?

```
Register key:

Reads as 0xFA05

On writes, write 0x5FA to VECTKEY, otherwise the write is ignored.```

**Comment by hdhoang** [comment]
Thanks for the review. I started out with `write(0x05fa_0004)`, then adapted an SO's answer mask-preserving write into the `modify` call. Neither had the desired effect.

However there's a difference between overwriting and modifying:
- overwrite: the LEDs turn off while the Reset key is held down, and turn back on when released
- modify: the first `set_theme` call runs

I'll try to add some `syst.cvr` waiting to see further effect.

**Comment by ah-** [comment]
Sounds like the overwrite method is working.
Not sure what exactly it resets, maybe it just runs user code again?

Maybe put something into main.rs init so you can see? It should now turn on leds on startup.
