### ISSUE TITLE
[feature] Support for cursor control.

### ISSUE THREAD

**Issue by MozzieBytes** [ah-/anne-key#56]
# Support for cursor control

Would be good to have cursor control as one of the available options in function layers. This would be great when using the keyboard without a dedicated mouse.

**Comment by ah-** [comment]
Agreed, that'd be really nice. If anyone wants to give this a go I'm happy to point into the right direction :)

**Comment by Dafondo** [comment]
Ok, my friend and I scanned through some of the code base and think we have a basic grasp on how it works. @ah- can you give us some pointers on getting started with cursor control?
