### ISSUE TITLE
[Feature] Implementation of QMK's Tap Dance

### ISSUE THREAD

**Issue by xobtoor** [ah-/anne-key#61]
It would be nice to have some of the [Tap Dance](https://docs.qmk.fm/features/tap-dance) functionality.

When i used it first (formerly known as e.g. double tap action) i felt in love with this feature it basically allows you to give a key more than one 'action' like: When you press and release 'A' just type an 'a', but when you press and hold 'A' you'll get 'Shift' this is called ACTION_TAP_DANCE_DOUBLE in Tap Dance.

You can find more details in the [docs](https://docs.qmk.fm/features/tap-dance).

**Comment by bburky** [comment]
I'm not sure if this is the same feature, but using another tool, [Karabiner](https://pqrs.org/osx/karabiner/), I once double bound caps lock as <kbd>ctrl</kbd> and <kbd>esc</kbd>. When pressed alone it would send <kbd>esc</kbd>, but only when pressed in combination with another key it would send <kbd>ctrl</kbd>.

Is that the definition of "hold" that QMK uses? Or is it time based?

**Comment by WishCow** [comment]
I don't think @r00tbox describes tap dance correctly. Tap dance is when a button has multiple outputs, based on how many times it is pressed, it is not related to holding down the button.

https://jayliu50.github.io/qmk-cheatsheet/ Search for "tap dance".

It would still be a great addition to the firmware what @r00tbox is describing.
